gestion_boutique_param:
    resource: "@GestionBoutiqueParamBundle/Resources/config/routing.yml"
    prefix:   /param

gestion_boutique_app:
    resource: "@GestionBoutiqueAppBundle/Resources/config/routing.yml"
    prefix:   /application

gestion_boutique_user:
    resource: "@GestionBoutiqueUserBundle/Resources/config/routing.yml"
    prefix:   /

gestion_boutique_main:
    resource: "@GestionBoutiqueMainBundle/Resources/config/routing.yml"
    prefix:   /accueil

login:
    path: /login
    defaults:
        _controller: GestionBoutiqueUserBundle:Security:login

login_check:
    path: /login_check

logout:
    path: /logout
