# app/config/security.yml

security:
    encoders:
        Symfony\Component\Security\Core\User\User: sha512
        GestionBoutique\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN : ROLE_ADMIN
        ROLE_CLIENT: ROLE_CLIENT
        
    providers:
        user_provider:
            entity:
                class: GestionBoutiqueUserBundle:User
                property: username
    firewalls:
        main:
            pattern:  ^/
            anonymous: true
            provider: user_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: login
    access_control:
         - { path: ^/admin, roles: ROLE_ADMIN }
         - { path: ^/client, roles: ROLE_CLIENT }