gestion_boutique_main_homepage:
    path:     /
    defaults: { _controller: GestionBoutiqueMainBundle:Acceuil:acceuil }
page_application:
    path:     /
    defaults: { _controller: GestionBoutiqueAppBundle:Application:index }
