page_profil:
    path:  /param/profil
    defaults: { _controller : GestionBoutiqueParamBundle:Profil:profil }
page_verrouiller:
    path:  /param/verrouiller
    defaults: { _controller : GestionBoutiqueParamBundle:Verrouiller:verrouiller }
page_application:
    path:     /application
    defaults: { _controller: GestionBoutiqueAppBundle:Application:index }
list_articles:
    path:     /application/article/listArticles
    defaults: { _controller: GestionBoutiqueAppBundle:Article:listArticles }
list_fournisseurs:
    path:     /application/fournisseur/listFournisseurs
    defaults: { _controller: GestionBoutiqueAppBundle:Fournisseur:listFournisseur }