login:
    path:   /login
    defaults:
        _controller: GestionBoutiqueUserBundle:Security:login
page_application:
    path:      /
    defaults: { _controller: GestionBoutiqueAppBundle:Application:index }
list_articles:
    path:     /article/listArticles
    defaults: { _controller: GestionBoutiqueAppBundle:Article:listArticle }
list_fournisseurs:
    path:     /fournisseur/listFournisseurs
    defaults: { _controller: GestionBoutiqueAppBundle:Fournisseur:listFournisseur }
list_clients:
    path:     /client/listClients
    defaults: { _controller: GestionBoutiqueAppBundle:Client:listClient }
view_fournisseur:
    path:     /fournisseur/viewFournisseur/{id}
    defaults: { _controller: GestionBoutiqueAppBundle:Fournisseur:viewFournisseur }
edit_fournisseur:
    path:     /fournisseur/editFournisseur/{id}
    defaults: { _controller: GestionBoutiqueAppBundle:Fournisseur:editFournisseur }
trash_fournisseur:
    path:     /fournisseur/trashFournisseur/{id}
    defaults: { _controller: GestionBoutiqueAppBundle:Fournisseur:trashFournisseur }
page_profil:
    path:  /param/profil
    defaults: { _controller : GestionBoutiqueParamBundle:Profil:profil }
page_verrouiller:
    path:  /param/verrouiller
    defaults: { _controller : GestionBoutiqueParamBundle:Verrouiller:verrouiller }
list_ventes:
    path:  /vente/listVentes
    defaults: { _controller : GestionBoutiqueAppBundle:Vente:vente }
