<?php

namespace GestionBoutique\AppBundle\Repository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends \Doctrine\ORM\EntityRepository
{
    public function dropClientById($id){

        $sql ='DELETE FROM GestionBoutiqueAppBundle:Client c WHERE c ='.$id.' ';
        $sqlQuery = $this->getEntityManager()->createQuery($sql);
        $sqlQuery->execute();
    }
}
