<?php

namespace GestionBoutique\AppBundle\Repository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function createAlphabeticalQueryBuilder(){

        return $this->createQueryBuilder('fournisseur')
            ->orderBy('fournisseur.prenom','ASC');
    }
}
