<?php

namespace GestionBoutique\AppBundle\Repository;

/**
 * FournisseurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FournisseurRepository extends \Doctrine\ORM\EntityRepository
{
    public function createAlphabeticalQueryBuilder(){

        return $this->createQueryBuilder('fournisseur')
            ->orderBy('fournisseur.prenom','ASC');
    }
    public function dropFournisseurById($id){

        $sql ='DELETE FROM GestionBoutiqueAppBundle:Fournisseur f WHERE f ='.$id.' ';
        $sqlQuery = $this->getEntityManager()->createQuery($sql);
        $sqlQuery->execute();
    }
}
