GestionBoutique\AppBundle\Entity\Article:
    type: entity
    table: null
    repositoryClass: GestionBoutique\AppBundle\Repository\ArticleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        libelle:
            type: string
            length: 255
        quantite:
            type: integer
        prixVenteUnit:
            type: float
        prixAchatUnit:
            type: float
        description:
            type: string
            length: 255
    manyToOne:
        fournisseur:
            targetEntity: Fournisseur
            inversedBy: articles
            joinColumn:
                name: fournisseur_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
